#!/bin/sh

MOUNT_POINT=/mnt/usb

if [ ! -f $MDEV ]; then
	if [ ! -d $MOUNT_POINT ]; then
		mkdir -p $MOUNT_POINT
	fi

	if [ ! -d $MOUNT_POINT ]; then
		echo "${MOUNT_POINT} can not create" > /dev/console
		exit
	fi

	echo "start to mount ${MDEV} ${MOUNT_POINT}" > /dev/console

	mount -o iocharset=utf8,codepage=936 /dev/$MDEV $MOUNT_POINT
	if [ $? -eq 0 ]; then
		echo "mount ${MDEV} ${MOUNT_POINT} ok" > /dev/console
	else
		echo "mount ${MDEV} ${MOUNT_POINT} failed" > /dev/console
	fi
fi
